GET http://localhost:3000/movies/
###

POST http://localhost:3000/movies/

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}
###

GET http://localhost:3000/movies/1/
###

PUT http://localhost:3000/movies/50/

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}
###

DELETE http:localhost:3000/movies/1/